# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric 1.20.1 properties
# check these on https://fabricmc.net/develop
minecraft_1_20_1_version=1.20.1
yarn_1_20_1_mappings=1.20.1+build.10
fabric_loader_1_20_1_version=0.19.3
loom_1_20_1_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.2.2-beta
maven_group=com.timelord

# Dependencies
fabric_api_1_20_1_version=0.92.11+1.20.1

# Fabric 1.21.1 properties
minecraft_1_21_1_version=1.21.1
yarn_1_21_1_mappings=1.21.1+build.3
fabric_loader_1_21_1_version=0.19.3
loom_1_21_1_version=1.17-SNAPSHOT
fabric_api_1_21_1_version=0.116.15+1.21.1
